name: Preview

on:
  push:
    branches: [disabled-for-now] # TODO: add main branch when osgeosuomi has access to project in test.pypi.org

concurrency:
  group: build-${{ github.head_ref }}

jobs:
  build:
    name: Build and publish release
    runs-on: ubuntu-latest
    environment:
      name: pypi-release
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install Python 3.13
        run: uv python install 3.13
      - name: Build
        run: uv build
      - name: Publish
        run: uv publish --index testpypi
