name: release & publish workflow

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

jobs:
  build:
    name: Build and publish release
    runs-on: ubuntu-latest
    environment:
      name: pypi-release
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install Python 3.13
        run: uv python install 3.13
      - name: Build
        run: uv build
      - name: Publish
        run: uv publish
      - name: Get version from tag
        id: tag_name
        run: |
          echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
        shell: bash
      - name: create github release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*
          draft: false
          prerelease: false
