name: Validations for pull requests

on:
  pull_request:
    branches: [main]

jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - uses: pre-commit/action@v3.0.1

  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: qgis/qgis:${{ matrix.qgis-image-tag }}
    strategy:
      matrix:
        qgis-image-tag:
          - release-3_34
          - "3.44"
          - "4.0-trixie"
          - latest
      fail-fast: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v6
      - run: |
          apt update
          apt install -y python3-venv curl
      - run: |
          python3 -m venv --system-site-packages .venv
      - run: |
          .venv/bin/pip3 install -q -U uv
          .venv/bin/uv sync --locked
      - name: Run tests
        run: .venv/bin/pytest --qgis_disable_gui
        env:
          QGIS_PLUGIN_IN_CI: 1
          QGIS_PLUGIN_TOOLS_IN_CI: 1

  build:
    name: Build wheels and source distribution
    needs: [code-style, test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install build dependencies
      run: python -m pip install --upgrade build
    - name: Build
      run:
        python -m build

    - uses: actions/upload-artifact@v6
      with:
        name: artifacts
        path: dist/*
        if-no-files-found: error
